<div class="custom-block-authentication" id="customer-forgotpassword-popup" style="display: none;">
    <div class="block-customer-forgot-password">
        <div class="block-title">
            <span class="custom-popup-title" id="block-customer-ajax-forgot-password-heading" aria-level="2">
                <?= __('Forgot Your Password?') ?>
            </span>
        </div>
        <div class="block-content" aria-labelledby="block-customer-forgot-password-heading">
            <form class="form form-forgot-password" method="post" id="ajax-forgot-password-form" action="<?= $block->getForgotpasswordActionPost() ?>">
                <div class="fieldset login">
                    <div class="field email required">
                        <label class="label" for="ajax-forgot-password-email">
                            <span class="custom-field"><?= __('Email Address') ?></span>
                        </label>
                        <div class="control">
                            <input name="username" id="ajax-forgot-password-email" type="email" class="input-text" data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>

                    <!-- CAPTCHA -->
                    <!-- <?//= $block->getChildHtml('form.additional.info'); ?> -->

                    <div class="actions-toolbar">
                        <div class="secondary link-forgot-password">
                            <a class="action link-forgot-password" id="customer-sign-in-popup">
                                <span><?= __('Back to Sign in') ?></span>
                            </a>
                        </div>
                        <div class="primary field-submit-form">
                            <button type="submit" class="action action-register primary" name="send" id="ajax-forgot-password-send">
                                <span><?= __('Reset my password') ?></span>
                            </button>
                        </div>
                    </div>
                    <div class="messages">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#customer-forgotpassword-popup": {
            "CustomModules_AjaxLogin/js/action/popup-forgotpassword": {
                "popupTitle": "<?= __('Forgot Your Password') ?>",
                "innerWidth": "400"
            }
        }
    }
</script>