<?php

use Magento\Customer\Block\Account\AuthenticationPopup;
use CustomModules\AjaxLogin\Helper\Data;

/**
 * @var AuthenticationPopup $block
*/

$_helper = $this->helper(Data::class)->isEnabled();
?>
<?php if ($_helper) : ?>
<div class="custom-block-authentication" id="customer-forgotpassword-popup" style="display: none;">
    <div class="block-customer-forgotpassword">
        <div class="block-title">
            <span class="custom-popup-title" id="block-customer-ajaxlogin-heading" aria-level="2">
                <?= __('Forgot your password?') ?>
            </span>
        </div>
        <div class="block-content" aria-labelledby="block-customer-forgotpassword-heading">
            <p><?= __('Please enter your email address below to receive a password reset link.') ?></p>
            <form class="form form-forgotpassword" method="post" id="ajaxlogin-form-forgotpassword" action="<?= $block->getUrl('ajaxlogin/ajax/forgotpassword') ?>">
                <div class="fieldset forgotpassword">
                    <div class="field email required">
                        <label class="label" for="ajaxlogin-email-forgotpassword">
                            <span class="custom-field"><?= __('Email Address') ?></span>
                        </label>
                        <div class="control">
                            <input name="username" id="ajaxlogin-email-forgotpassword" type="email" class="input-text" data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <div class="actions-toolbar">
                        <div class="secondary link-forgot-password">
                            <a class="action link-forgot-password" id="forgotpassword-popup" href="<?= $block->getCustomerForgotPasswordUrl() ?>">
                                <span><?= __('Back to Sing In') ?></span>
                            </a>
                        </div>
                        <div class="primary field-submit-form">
                            <button type="submit" class="action action-forgotpassword secondary" name="send" id="ajaxlogin-send-forgotpassword">
                                <span><?= __('Sign In') ?></span>
                            </button>
                        </div>
                    </div>
                    <div class="messages">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#customer-forgotpassword-popup": {
            "CustomModules_AjaxLogin/js/action/customer-popups": {
                "popupTitle": "<?= __('Sign In') ?>",
                "innerWidth": "400"
            }
        }
    }
</script>
<?php endif; ?>