<?php

use Magento\Customer\Block\Account\AuthenticationPopup;
use Magezil\AjaxLogin\Helper\Data;

/**
 * @var AuthenticationPopup $block
 */

$_helper = $this->helper(Data::class)->isEnabled();
?>
<?php if ($_helper) : ?>
    <div class="block-popup-forgotpassword" id="customer_forgotpassword_popup" style="display: none;">
        <div class="block block-customer-forgotpassword">
            <div class="popup-title">
                <span class="custom-popup-title" aria-level="2">
                    <?= __('Forgot your password?') ?>
                </span>
            </div>
            <div class="block-popup-content">
                <p><?= __('Please enter your email address below to receive a password reset link.') ?></p>
                <form class="form form-popup-forgotpassword" method="POST" id="forgotpassword_popup_form" action="<?= $block->getUrl('ajaxlogin/ajax/forgotpassword') ?>">
                    <fieldset class="fieldset">
                        <div class="field email required">
                            <label class="label" for="forgotpassword_email">
                                <span class="custom-field"><?= __('Email Address') ?></span>
                            </label>
                            <div class="control">
                                <input name="username" id="forgotpassword_email" type="email" class="input-text" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="actions-toolbar">
                            <div class="secondary link-sign-in">
                                <a class="action link-sign-in" id="back_sign_in" href="<?= $block->getSignInUrl() ?>">
                                    <span><?= __('Back to Sing In') ?></span>
                                </a>
                            </div>
                            <div class="primary field-submit-form">
                                <button type="submit" class="action action-forgotpassword secondary" name="send" id="forgotpassword_popup_submit">
                                    <span><?= __('Sign In') ?></span>
                                </button>
                            </div>
                        </div>
                        <div class="messages">
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
        "#customer_forgotpassword_popup": {
            "Magezil_AjaxLogin/js/action/forgotpassword-popup": {
                "popupTitle": "<?= __('Sign In') ?>",
                "innerWidth": "400"
            }
        }
    }
</script>
<?php endif; ?>