<?php

use Magento\Customer\Block\Account\AuthenticationPopup;
use Magezil\AjaxLogin\Helper\Data;

/**
 * @var AuthenticationPopup $block
 **/

$_helper = $this->helper(Data::class)->isEnabled();
?>
<?php if ($_helper) : ?>
    <div class="block-popup-login" id="customer_login_popup" style="display: none;">
        <div class="block block-popup-new-customer">
            <div class="block-popup-title">
                <span class="popup-title" aria-level="1">
                    <?= __('Create New Customer Account') ?>
                </span>
            </div>
            <div class="block-content">
                <p><?= __('Creating an account has many benefits:') ?></p>
                <ul>
                    <li><?= __('See order and shipping status') ?></li>
                    <li><?= __('Track order history') ?></li>
                    <li><?= __('Check out faster') ?></li>
                    <li><?= __('Keep more than one address and much more') ?></li>
                </ul>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <a class="action action-register primary" href="<?= $block->getCustomerRegisterUrlUrl() ?>">
                        <span><?= __('Create an Account') ?></span>
                    </a>
                </div>
            </div>
        </div>
        <div class="block-customer-login">
            <div class="block-popup-title">
                <span class="popup-title" aria-level="2">
                    <?= __('Customer Login') ?>
                </span>
            </div>
            <div class="block-popup-content">
                <form class="form form-popup-login" method="POST" id="login_popup_form" action="<?= $block->getUrl('ajaxlogin/ajax/login') ?>">
                    <fieldset class="fieldset">
                        <div class="field email required">
                            <label class="label" for="login_popup_email">
                                <span class="custom-field"><?= __('Email Address') ?></span>
                            </label>
                            <div class="control">
                                <input name="username" id="login_popup_email" type="email" class="input-text" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field password required">
                            <label for="login_popup_password" class="label">
                                <span class="custom-field"><?= __('Password') ?></span>
                            </label>
                            <div class="control">
                                <input name="password" type="password" class="input-text" id="login_popup_password" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="actions-toolbar">
                            <div class="secondary link-forgot-password">
                                <a class="action link-forgot-password" id="forgotpassword_popup" href="<?= $block->getCustomerForgotPasswordUrl() ?>">
                                    <span><?= __('Forgot Your Password?') ?></span>
                                </a>
                            </div>
                            <div class="primary field-submit-form">
                                <button type="submit" class="action action-login secondary" name="send" id="ajaxlogin-send">
                                    <span><?= __('Sign In') ?></span>
                                </button>
                            </div>
                        </div>
                        <div class="message-popup">
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
        "#customer_login_popup": {
            "Magezil_AjaxLogin/js/action/login-popup": {
                "popupTitle": "<?= __('Sign In') ?>",
                "innerWidth": "400"
            }
        }
    }
</script>
<?php endif; ?>