<div class="block-authentication-lucas" id="customer-login-popup" style="display: none">
    <div class="block block-new-customer" style="float: left; width: 50%; box-sizing: border-box;">
        <div class="block-title">
            <span id="block-new-customer-heading" aria-level="1"><?= __('My Create an Account') ?></span>
        </div>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <p><?= __('Creating an account has many benefits:') ?></p>
            <ul>
                <li><?= __('See order and shipping status') ?></li>
                <li><?= __('Track order history') ?></li>
                <li><?= __('Check out faster') ?></li>
            </ul>
            <div class="actions-toolbar">
                <div class="primary">
                    <a class="action action-register primary">
                        <span><?= __('Create an Account') ?></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="block block-customer-login" style="float: left; width: 50%; box-sizing: border-box;">
        <div class="block-title">
            <strong id="block-customer-ajaxlogin-heading" aria-level="2"><?= __('Login') ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form form-login" method="post" id="ajaxlogin-form" action="<?= $block->getUrl('ajaxlogin/ajax/login') ?>">
                <div class="fieldset login">
                    <div class="field email required">
                        <label class="label" for="ajaxlogin-email">
                            <span><?= __('Email Address') ?></span>
                        </label>
                        <div class="control">
                            <input name="username" id="ajaxlogin-email" type="email" class="input-text" data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <div class="field password required">
                        <label for="ajaxlogin-pass" class="label">
                            <span><?= __('Password') ?></span>
                        </label>
                        <div class="control">
                            <input name="password" type="password" class="input-text" id="ajaxlogin-pass" data-validate="{required:true}">
                        </div>
                    </div>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit" class="action action-login secondary" name="send" id="ajaxlogin-send">
                                <span><?= __('Sign In') ?></span>
                            </button>
                        </div>
                        <div class="secondary">
                            <a class="action" id="forgotpassword-popup">
                                <span><?= __('Forgot Your Password?') ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#customer-login-popup": {
            "CustomModules_AjaxLogin/js/action/customer-popups": {
                "popupTitle": "<?= __('Sign In') ?>",
                "innerWidth": "400"
            }
        }
    }
</script>