<?php

/** @var \Magento\Customer\Block\Account\AuthenticationPopup $block */

$_helper = $this->helper(\CustomModules\AjaxLogin\Helper\Data::class);
?>
<?php if ($_helper->isEnabled()) : ?>
    <div id="ajaxlogin-popup" data-bind="scope:'ajaxLogin'" style="display: none;">
        <script>
            window.ajaxLogin = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
        </script>
        <!-- ko template: getTemplate() -->
        <!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#ajaxlogin-popup": {
                    "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                }
            }
        </script>
    </div>
<?php endif; ?>